--
-- Copyright 2017 ZTE Corporation.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
/******************DROP OLD DATABASE AND USER***************************/
USE MYSQL;
DROP DATABASE IF  EXISTS HOLMES;
DELETE FROM USER WHERE USER='HOLMES';
FLUSH PRIVILEGES;

/******************CREATE NEW DATABASE AND USER***************************/
CREATE DATABASE HOLMES CHARACTER SET UTF8;

GRANT ALL PRIVILEGES ON HOLMES.* TO 'HOLMES'@'%' IDENTIFIED BY 'HOLMES' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON MYSQL.* TO 'HOLMES'@'%' IDENTIFIED BY 'HOLMES' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON CATALOG.* TO 'HOLMES'@'LOCALHOST' IDENTIFIED BY 'HOLMES' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON MYSQL.* TO 'HOLMES'@'LOCALHOST' IDENTIFIED BY 'HOLMES' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE HOLMES;
SET NAMES 'UTF8';
/******************DELETE OLD TABLE AND CREATE NEW***************************/
USE HOLMES;
DROP TABLE IF EXISTS APLUS_RULE;
CREATE TABLE APLUS_RULE (
  RID VARCHAR(30) NOT NULL,
  NAME VARCHAR(150) NOT NULL,
  DESCRIPTION VARCHAR(4000) NULL,
  ENABLE INT(1) NOT NULL,
  TEMPLATEID INT(10) NOT NULL,
  ENGINEID VARCHAR(20)  NOT NULL,
  ENGINETYPE VARCHAR(20)  NOT NULL,
  CREATOR VARCHAR(20)  NOT NULL,
  CREATETIME DATETIME NOT NULL,
  UPDATOR VARCHAR(20)  NULL,
  UPDATETIME DATETIME NULL,
  PARAMS VARCHAR(4000) NULL,
  CONTENT VARCHAR(4000) NOT NULL,
  VENDOR VARCHAR(100)  NOT NULL,
  PACKAGE VARCHAR(255) NULL,
  PRIMARY KEY (RID),
  UNIQUE KEY NAME (NAME),
  KEY IDX_APLUS_RULE_ENABLE (ENABLE),
  KEY IDX_APLUS_RULE_TEMPLATEID (TEMPLATEID),
  KEY IDX_APLUS_RULE_ENGINEID (ENGINEID),
  KEY IDX_APLUS_RULE_ENGINETYPE (ENGINETYPE)
)

